### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by fazakis** [mariuz/linux-0.01#1]
hello friend, i use 64bit ubuntu 13.10 as OS i clone your repository (linux-0.01), i extract hd_oldlinux.img.zip and run: qemu -hdb hd_oldlinux.img -fda linux0.01-3.5.img -boot a then qemu gives me output: Partition Table ok Kernel Panic: Unexpected HD interrupt, can you help with this? Thanks in advance.

**Comment by skypool** [comment]
Linux-0.01 based on linux-0.01-rm-3.5-rt20110112.patch works as far as I know under Ubuntu 12.04 with QEMU 1.0.50 (qemu-7fe7b68 on github) and gcc 4.6.3.

I tried to run it under Ubuntu 14.04 with qemu 2.2.0 and gcc 4.8.2 (or 4.9.2). It failed. As far as I could see, is the error in gcc 4.8.2's code generation. Inlining functions and inline assembly code lead to a missing ESI assignment in namei.c function match. gcc 4.6.3 will generate the correct code.

To avoid this error tell gcc not to inline the match function in namei.c by adding __attribute__ ((noinline)).

Another "error" has to do with the I/O handling in QEMU. As far as I could find out, QEMU changed its I/O handling after qemu-7fe7b68 (coroutines). Therefore the hd interrupt timings had changed. In hd.c function read_intr() I deleted the return after the second port_read and added one below the first port_read function.

With this two changes I had no problems running Linux-0.01 with qemu 2.2.0 and gcc 4.9.2.

**Comment by kensully** [comment]
@skypool Thank you for your valuable info. I applied the patch to Linux-0.01. However I didn't locate `hd.c` file in qemu source code in github https://github.com/qemu/qemu.git  
I hope you help us to fix `Unexpected HD interrupt` issue.

**Comment by skypool** [comment]
hd.c can be found in https://github.com/mariuz/linux-0.01/blob/master/kernel/hd.c. It's part of Linux-0.01 not QEMU.

**Comment by kensully** [comment]
@skypool Wow! You must be a genius. Thanks to you I have a kernel toy now.
All the best.
Kenn

**Comment by isoux** [comment]
@skypool:
> I tried to run it under Ubuntu 14.04 with qemu 2.2.0 and gcc 4.8.2 (or 4.9.2). It failed. As far as I could see, is the error in gcc 4.8.2's code generation. Inlining functions and inline assembly code lead to a missing ESI assignment in namei.c function match. gcc 4.6.3 will generate the correct code.
> 
> To avoid this error tell gcc not to inline the match function in namei.c by adding **attribute** ((noinline)).
> 
> Another "error" has to do with the I/O handling in QEMU. As far as I could find out, QEMU changed its I/O handling after qemu-7fe7b68 (coroutines). Therefore the hd interrupt timings had changed. In hd.c function read_intr() I deleted the return after the second port_read and added one below the first port_read function.

@skypool Thanks for the valuable information,
By the your advice I've already changed the code on my forked repository.
