### ISSUE TITLE
Ubuntu 20.04 support?

### ISSUE THREAD

**Issue by liudonghua123** [mariuz/linux-0.01#4]
How about making it work on ubuntu 20.04?

**Comment by liudonghua123** [comment]
I tried to compile and run on my latest kali which is based on ubuntu 20.04. The compile job is ok, but when I tried to run it via `qemu-system-i386 -hdb hd_oldlinux.img -fda Image -boot a`, then a infinite error loop occurred.

see the following video for more details.

https://user-images.githubusercontent.com/2276718/141945098-8d397aa4-6aed-42bf-9858-ababa55ceaa3.mp4

**Comment by skypool** [comment]
You have to add `-M pc-i440fx-2.5` or `-global isa-fdc.fallback=144` to qemu, sind the fallback of the fdc has changed from 1.44MB to 2.88MB [https://patchwork.kernel.org/project/qemu-devel/patch/1453272694-17106-13-git-send-email-jsnow@redhat.com/](https://patchwork.kernel.org/project/qemu-devel/patch/1453272694-17106-13-git-send-email-jsnow@redhat.com/)

**Comment by liudonghua123** [comment]
Yes, `qemu-system-i386 -hdb hd_oldlinux.img -fda Image -boot a -M pc-i440fx-2.5` or `qemu-system-i386 -hdb hd_oldlinux.img -fda Image -boot a -global isa-fdc.fallback=144` works for me. Thanks!

So this project works on ubuntu 20.04 actually.

The following content in readme could be updated. 😄 
> I managed to compile this revised version of the first kernel on machines with Ubuntu 18.04 64 and 32 bit versions.
