### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by iddq** [mariuz/linux-0.01#5]
Do you have documentation of the changes you've made?

**Comment by mariuz** [comment]
I have made minimal changes to compile it on 64bit os , started from linux-0.01-rm-3.5.tar.gz , you can do a diff with that version 

https://mapopa.blogspot.com/2008/09/linux-0.html

**Comment by mariuz** [comment]
Initial patch was (from the blog comments) to build it on 64 bits distro 

https://github.com/mariuz/linux-0.01/commit/7a530753068d41b9e984b59754d9b9ffac20e177

the rest you can check in the github history 
https://github.com/mariuz/linux-0.01/commits/master
